package com.projeto_engenharia.projeto.enums;

public enum Especialidade {
    DESENVOLVIMENTO_WEB,
    MOBILE,
    SEGURANCA_DA_INFORMACAO,
    INTELIGENCIA_ARTIFICIAL,
    CIENCIA_DE_DADOS,
    ENGENHARIA_DE_SOFTWARE,
    REDES_DE_COMPUTADORES,
    SISTEMAS_EMBARCADOS,
    BANCO_DE_DADOS,
    UX_DESIGN,
    DESENVOLVIMENTO_DE_JOGOS,
    CLOUD_COMPUTING,
    DEVOPS,
    CIBERSEGURANCA,
    REALIDADE_VIRTUAL_AUMENTADA
}

